"""
에러 코드 정의 (design.md §5)

FastAPI 전역 예외 핸들러(app/main.py)가 AppError를
{"error": {"code": ..., "message": ...}} 형태의 JSON으로 변환한다.
"""

from __future__ import annotations


class AppError(Exception):
    """API 계층에서 사용하는 표준 에러.

    code: 클라이언트가 분기할 수 있는 안정적 식별자
    message: 사람이 읽는 설명 (민감 정보 포함 금지)
    status_code: HTTP 상태 코드
    """

    def __init__(self, code: str, message: str, status_code: int) -> None:
        self.code = code
        self.message = message
        self.status_code = status_code
        super().__init__(message)


# ──────────────────────────────────────────────
# 에러 코드 상수 — design.md §5
# ──────────────────────────────────────────────

UNAUTHORIZED = "UNAUTHORIZED"  # 401 — 시크릿 누락/불일치
FORBIDDEN = "FORBIDDEN"  # 403 — 본인 소유가 아닌 리소스 접근
SESSION_NOT_FOUND = "SESSION_NOT_FOUND"  # 404
PARTICIPANT_NOT_FOUND = "PARTICIPANT_NOT_FOUND"  # 404
INVALID_INVITE_TOKEN = "INVALID_INVITE_TOKEN"  # 404
ANALYSIS_NOT_FOUND = "ANALYSIS_NOT_FOUND"  # 404
VALIDATION_ERROR = "VALIDATION_ERROR"  # 422
INVALID_MEMBER_COUNT = "INVALID_MEMBER_COUNT"  # 422
MEMBER_COUNT_BELOW_SUBMITTED = "MEMBER_COUNT_BELOW_SUBMITTED"  # 422
DUPLICATE_SUBMISSION_METHOD = "DUPLICATE_SUBMISSION_METHOD"  # 409
SUBMISSION_LOCKED = "SUBMISSION_LOCKED"  # 409
ANALYSIS_ALREADY_RUNNING = "ANALYSIS_ALREADY_RUNNING"  # 409
ANALYSIS_NOT_READY = "ANALYSIS_NOT_READY"  # 409
SESSION_EXPIRED = "SESSION_EXPIRED"  # 410
INTERNAL_ERROR = "INTERNAL_ERROR"  # 500

# ── 퀘스트 / 워크스페이스 (SPEC_V5) ──
QUEST_ASSIGNMENT_NOT_FOUND = "QUEST_ASSIGNMENT_NOT_FOUND"  # 404
NO_ACTIVE_QUEST = "NO_ACTIVE_QUEST"  # 404
QUEST_CATALOG_UNAVAILABLE = "QUEST_CATALOG_UNAVAILABLE"  # 409 — 유효한 후보가 전혀 없음
QUEST_ALREADY_FINALIZED = "QUEST_ALREADY_FINALIZED"  # 409 — 이미 COMPLETED/SKIPPED
QUEST_NOT_STARTED = "QUEST_NOT_STARTED"  # 409 — IN_PROGRESS 이전 상태에서 완료/응답 시도
COMPLETION_CONDITION_NOT_MET = "COMPLETION_CONDITION_NOT_MET"  # 409
WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"  # 404
WORKSPACE_NOT_READY = "WORKSPACE_NOT_READY"  # 409 — 분석 미완료 또는 퀘스트 미종료
TASK_NOT_FOUND = "TASK_NOT_FOUND"  # 404
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"  # 404

# ── 워크스페이스 도구 확장 (SPEC_V5.3) ──
MEETING_NOTE_NOT_FOUND = "MEETING_NOTE_NOT_FOUND"  # 404
CHECKLIST_ITEM_NOT_FOUND = "CHECKLIST_ITEM_NOT_FOUND"  # 404
DECISION_NOT_FOUND = "DECISION_NOT_FOUND"  # 404
DECISION_OPTION_NOT_FOUND = "DECISION_OPTION_NOT_FOUND"  # 404
DECISION_ALREADY_FINALIZED = "DECISION_ALREADY_FINALIZED"  # 409


# ──────────────────────────────────────────────
# 코드 → 기본 HTTP 상태 매핑 (편의 헬퍼)
# ──────────────────────────────────────────────

_STATUS_BY_CODE: dict[str, int] = {
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    SESSION_NOT_FOUND: 404,
    PARTICIPANT_NOT_FOUND: 404,
    INVALID_INVITE_TOKEN: 404,
    ANALYSIS_NOT_FOUND: 404,
    VALIDATION_ERROR: 422,
    INVALID_MEMBER_COUNT: 422,
    MEMBER_COUNT_BELOW_SUBMITTED: 422,
    DUPLICATE_SUBMISSION_METHOD: 409,
    SUBMISSION_LOCKED: 409,
    ANALYSIS_ALREADY_RUNNING: 409,
    ANALYSIS_NOT_READY: 409,
    SESSION_EXPIRED: 410,
    INTERNAL_ERROR: 500,
    QUEST_ASSIGNMENT_NOT_FOUND: 404,
    NO_ACTIVE_QUEST: 404,
    QUEST_CATALOG_UNAVAILABLE: 409,
    QUEST_ALREADY_FINALIZED: 409,
    QUEST_NOT_STARTED: 409,
    COMPLETION_CONDITION_NOT_MET: 409,
    WORKSPACE_NOT_FOUND: 404,
    WORKSPACE_NOT_READY: 409,
    TASK_NOT_FOUND: 404,
    RESOURCE_NOT_FOUND: 404,
    MEETING_NOTE_NOT_FOUND: 404,
    CHECKLIST_ITEM_NOT_FOUND: 404,
    DECISION_NOT_FOUND: 404,
    DECISION_OPTION_NOT_FOUND: 404,
    DECISION_ALREADY_FINALIZED: 409,
}


def app_error(code: str, message: str) -> AppError:
    """코드에 대응하는 기본 상태 코드로 AppError를 만드는 헬퍼."""
    return AppError(code=code, message=message, status_code=_STATUS_BY_CODE.get(code, 500))
